### PR TITLE
Adding WiFiManager Example Sketches

### PR DESCRIPTION
**Pull request by bradrblack**
** Scope: Added example sketch to use WiFiManager to configure SSID and Password and connect to WiFi on ESP8266 and ESP32 microcontrollers.  No need to hard-code WiFi parameters in your sketch that connects to AdafruitIO.

** Limitations: WiFiManager supports ESP8266 and ESP32 boards only.

** Tests: Tested using 4.2.2 AdafruitIO library on ESP8266 and ESP32 microcontrollers.  ESP32 requires newer WiFiManager development branch - tested with: https://github.com/tzapu/WiFiManager.git@^2.0.5-beta

### CODE REVIEW

**Review by brentru — CHANGES_REQUESTED** [review]
Please place this sketch in a folder such that the folder name exactly matches the sketch name.

Example path: examples/adafruitio_27_wifimanager/adafruitio_27_wifimanager.ino

**Comment by bradrblack** [comment]
I moved the sketch to a subfolder as requested.

**Comment by brentru** [comment]
@bradrblack  Almost there - please include `WiFiManager` in the `depends` list within `library.properties` (https://github.com/adafruit/Adafruit_IO_Arduino/blob/master/library.properties#L10)

**Comment by brentru** [comment]
Also - since these examples are only for the ESP8266 and ESP32.

Please place 2 **empty** files in **each** example folder:
`pyportal.test.skip`
`metro_m4_airliftlite.test.skip`

This will tell our CI to skip testing the examples you added for the SAMD platforms.

**Comment by bradrblack** [comment]
Made changes as requested.  I think the skip files need to start with a "." like ".pyportal.test.skip".   So I change to that.

**Comment by brentru** [comment]
@bradrblack Looks perfect. Thanks for adding this example, a lot of people on the forums ask about this so it'll be a great resource to point people towards.

Finally, please bump the version number in the library.properties file to 4.2.3. I'll merge and release once this is done.

**Review by brentru — APPROVED** [review]

**Pull request merged**
