### PR TITLE
Add Yun (Arduino Yun and Seeeduino Cloud) support

### PR DESCRIPTION
**Pull request by imrehorvath**
- **Scope of change**  Add support for the Arduino Yun and Seeeduino Cloud boards. Now the users of these boards can use the Adafruit IO too, however some limitations may apply.

- **Known limitations with this change.**  Due to the limited amount of SRAM (2.5kB) in the 32u4 and the dynamic memory intensive nature of some part of the Adafruit IO library may cause problems with the Yun. Testing has shown that if the remaining free dynamic memory reported at the end of the build process in the Arduino IDE gets below 1540 bytes or so, then the sketch starts behaving unstable. However this is an extension of the original library which adds support for new boards and does not limit the functionality of the existing ones.

- **Provided examples were all tested with the Yun**  Since I have a Yun only and not the other boards, I've tested the change with the Yun only. The results are the following. All but the 01 and 10 examples were working fine with the Yun. The last example (#10) works partially. The check for the feed and the dashboard was working. Also the creation of these was working fine. However adding the blocks to the dashboard was not working. (probably because of the lack of free memory)

- ** SSL ** Unfortunately the currently available official firmware for the Yun (1.5.3) includes an older version of the Bridge library (101) which lacks support for SSL (via BridgeClient/BridgeSSLClient). However version 161 has been developed already and is available on GitHub. We hope that they will release a new firmware which includes this change too. For the REST API SSL is used already (Process/cURL).

I hope that extending the Adafruit IO library with support for the Yun and its clone enables the users of these boards to access the Adafruit IO, and I hope you find it useful, even though the know limitations!

@ladyada 
@tdicola 
@toddtreece

### CODE REVIEW

**Comment by imrehorvath** [comment]
@toddtreece  @tdicola @ladyada I've updated my extension (Yun support) to this library to catch up with the most recent changes. I've also tested the new examples dht22 and the group. I can confirm that they work just fine on the Yun! All is merged and does not conflict with the master. It can be pulled.

**Comment by imrehorvath** [comment]
Fork synced

**Comment by imrehorvath** [comment]
Fork synced once again

**Comment by brentru** [comment]
Your PR has remaining merge conflicts. @imrehorvath  Are you planning to resolve this, or can I close this PR?

**Pull request closed without merging**
